"""empty message

Revision ID: 648ea0c5986b
Revises: d2b812bfc13b
Create Date: 2024-06-30 23:06:29.321573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648ea0c5986b'
down_revision = 'd2b812bfc13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
